import { describe, expect, test } from 'bun:test';
import { calculatePart1, calculatePart2 } from './lib';

describe('day 08', () => {
  test('part 1', () => {
    const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
    const actual = calculatePart1(input);

    expect(actual).toBe(14);
  });

  test('part 2', () => {
    const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;
    const actual = calculatePart2(input);

    expect(actual).toBe(34);
  });
});
